apiVersion: v1
kind: Service
metadata:
  name: lumina-node
  namespace: lumina
  labels:
    app: lumina-node
spec:
  selector:
    app: lumina-node
  ports:
    - name: api
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: p2p
      port: 4000
      targetPort: 4000
      protocol: UDP
  type: ClusterIP
