apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumina-validator.fullname" . }}
  labels:
    app: {{ include "lumina-validator.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "lumina-validator.fullname" . }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: UDP
